server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:user_db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:111111}
    driver-class-name: com.mysql.cj.jdbc.Driver
