server:
  port: 8085

spring:
  application:
    name: node-agent

cae:
  node:
    id: 1
    node-code: "NODE_1"
    node-name: "Worker_Node_1"
    node-port: 8085
    max-concurrency: 2
    scheduler-base-url: "http://localhost:8084"
    task-base-url: "http://localhost:8083"
    work-root: "./node-agent-work"
    solver-ids: [1]
    solver-versions:
      "1": "v10"
